---

dev:
  app_host: 'dev.foo.com'
  user1:
    username: cheesemaster
    password: password

qa:
  app_host: 'qa.foo.com'
  user1:
    username: cheesemaster
    password: password

staging:
  app_host: 'stg.foo.com'
  user1:
    username: cheesemaster
    password: password

production:
  app_host: 'www.foo.com'
  user1:
    username: cheesemaster
    password: password
